import type { AIScriptResult } from '../types';
import { createDirectorPlan } from './planner';
import type { DirectorPlan, StylePreset } from './types';

/**
 * AIDirectorAgent: Master AI Director class.
 * Receives Gemini AIScriptResult and orchestrates the creation of a full
 * serializable DirectorPlan with 6-layer timeline specifications.
 */
export class AIDirectorAgent {
  /**
   * Directs a video project from AIScriptResult and optional StylePreset.
   * @param script AIScriptResult generated by Gemini AI
   * @param preset StylePreset (e.g. 'TikTok', 'YouTube', 'Commercial')
   * @returns Complete DirectorPlan
   */
  public directVideo(script: AIScriptResult, preset: StylePreset = 'YouTube'): DirectorPlan {
    return createDirectorPlan(script, preset);
  }

  /**
   * Serializes a DirectorPlan to JSON for storage in Project metadata.
   */
  public serializePlan(plan: DirectorPlan): string {
    return JSON.stringify(plan, null, 2);
  }

  /**
   * Deserializes JSON string back into a DirectorPlan.
   */
  public deserializePlan(jsonString: string): DirectorPlan {
    return JSON.parse(jsonString) as DirectorPlan;
  }
}

export const aiDirectorAgent = new AIDirectorAgent();
